name: pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - bzip2
  - ca-certificates
  - expat
  - libffi
  - openssl
  - pip
  - setuptools
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - numpy
  - scipy
  - scikit-image
  - pyvips
  - shapely
  - tifffile
  - openslide
  - tqdm
  - imageio
  - pillow
  - packaging
  - networkx
  - cffi
  - click
  - markdown-it-py
  - tomli
  - typing-extensions
  - pathspec
  - lazy-loader
  - pycparser
  - pycodestyle
  - pyflakes
  - pygments
  - pytest
  - iniconfig
  - exceptiongroup
  - imagecodecs
  - pip:
      - black==25.1.0
      - mypy-extensions==1.1.0
      - rich==14.1.0
      - opencv-python==4.12.0.88
      - openslide-python==1.4.2

